# Generated by Django 5.2.1 on 2026-02-11 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre identificativo del servidor', max_length=100)),
                ('ip_host', models.CharField(help_text='Dirección IP o Hostname', max_length=100)),
                ('puerto_tomcat', models.IntegerField(default=8080, help_text='Puerto donde corre Tomcat')),
                ('sistema_operativo', models.CharField(choices=[('windows', 'Windows'), ('linux', 'Linux')], default='windows', max_length=10)),
                ('usuario', models.CharField(blank=True, max_length=100, null=True)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('ultimo_check', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(default='Desconocido', max_length=20)),
            ],
        ),
    ]
