# Generated by Django 5.2.1 on 2026-02-11 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servidores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servidor',
            name='mensaje_error',
            field=models.TextField(blank=True, help_text='Último mensaje de error si falló la conexión', null=True),
        ),
        migrations.AddField(
            model_name='servidor',
            name='tipo_conexion',
            field=models.CharField(choices=[('winrm', 'WinRM (Windows Remoto)'), ('ssh', 'SSH (Linux / Windows OpenSSH)')], default='winrm', help_text='Protocolo de conexión remota', max_length=10),
        ),
    ]
