# Generated by Django 5.2.1 on 2026-02-11 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servidores', '0002_servidor_mensaje_error_servidor_tipo_conexion'),
    ]

    operations = [
        migrations.AddField(
            model_name='servidor',
            name='nombre_servicio',
            field=models.CharField(blank=True, help_text='Nombre real del servicio en el SO (Autodetectado)', max_length=100, null=True),
        ),
    ]
