# Generated by Django 5.2.1 on 2026-02-11 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servidores', '0003_servidor_nombre_servicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='servidor',
            name='puerto_conexion',
            field=models.IntegerField(blank=True, help_text='Puerto de conexión remota (SSH: 22, WinRM: 5985). Dejar vacío para default.', null=True),
        ),
    ]
