# Generated by Django 5.2.1 on 2026-02-11 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servidores', '0004_servidor_puerto_conexion'),
    ]

    operations = [
        migrations.AddField(
            model_name='servidor',
            name='tipo_instalacion',
            field=models.CharField(choices=[('servicio', 'Servicio del Sistema (Systemd/Windows)'), ('docker', 'Contenedor Docker')], default='servicio', help_text='Tipo de despliegue del aplicativo', max_length=10),
        ),
    ]
