# Generated by Django 5.2.1 on 2026-02-11 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servidores', '0005_servidor_tipo_instalacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servidor',
            name='tipo_instalacion',
            field=models.CharField(choices=[('sistema', 'Servicio del Sistema (Systemd/Services)'), ('docker', 'Contenedor Docker')], default='sistema', help_text='Tipo de despliegue: Servicio nativo o Docker', max_length=10),
        ),
    ]
