# Generated by Django 5.2.1 on 2026-02-12 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servidores', '0006_alter_servidor_tipo_instalacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servidor',
            name='tipo_conexion',
            field=models.CharField(choices=[('winrm', 'WinRM (Windows Remoto)'), ('ssh', 'SSH (Linux / Windows OpenSSH)'), ('local', 'Local (Este Equipo)')], default='winrm', help_text='Protocolo de conexión remota', max_length=10),
        ),
    ]
