# Generated by Django 5.2.1 on 2026-02-13 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servidores', '0007_alter_servidor_tipo_conexion'),
    ]

    operations = [
        migrations.AddField(
            model_name='servidor',
            name='snmp_community',
            field=models.CharField(default='public', help_text='Comunidad SNMP (ej. public)', max_length=50),
        ),
        migrations.AddField(
            model_name='servidor',
            name='snmp_port',
            field=models.IntegerField(default=161, help_text='Puerto UDP SNMP'),
        ),
    ]
