# Generated by Django 5.2.1 on 2026-02-19 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servidores', '0013_instancia_mensaje_error'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='snmp_community',
            field=models.CharField(default='public', help_text='Comunidad SNMP (ej. public)', max_length=50),
        ),
        migrations.AddField(
            model_name='host',
            name='snmp_port',
            field=models.IntegerField(default=161, help_text='Puerto UDP SNMP'),
        ),
    ]
