# Generated by Django 5.2.1 on 2026-02-19 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servidores', '0014_host_snmp_community_host_snmp_port'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Servidor',
        ),
    ]
