# Generated by Django 5.2.1 on 2026-02-19 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servidores', '0015_delete_servidor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='snmp_community',
            field=models.CharField(blank=True, default='public', help_text='Comunidad SNMP (ej. public)', max_length=50),
        ),
        migrations.AlterField(
            model_name='host',
            name='snmp_port',
            field=models.IntegerField(blank=True, default=161, help_text='Puerto UDP SNMP', null=True),
        ),
    ]
