from django.urls import path
from . import views

urlpatterns = [
    path('', views.navegacion, name='inicio'),
    path('documentacion/', views.documentacion, name='documentacion'),
    path('herramientas/', views.herramientas, name='herramientas'),
    path('config/db/', views.config_db, name='config_db'),
    path('config/monitoring/', views.config_monitoring, name='config_monitoring'),
    path('health/', views.health, name='health'),
    path('estado/', views.estado_sistema, name='estado_sistema'),
    path('estado/diagnostico/', views.estado_diagnostico, name='estado_diagnostico'),
    path('navegacion/', views.navegacion, name='navegacion'),
    path('navegacion/scan-host/', views.scan_host, name='scan_host'),
    path('navegacion/host/<int:pk>/eliminar/', views.eliminar_host, name='eliminar_host'),
    path('navegacion/host/<int:pk>/editar/', views.editar_host, name='editar_host'),
    path('navegacion/instancia/<int:pk>/verificar/', views.verificar_instancia, name='verificar_instancia'),
    path('navegacion/instancia/<int:pk>/eliminar/', views.eliminar_instancia, name='eliminar_instancia'),
    path('navegacion/instancia/<int:pk>/editar/', views.editar_instancia, name='editar_instancia'),
    path('navegacion/instancia/<int:pk>/<str:accion>/', views.controlar_instancia, name='controlar_instancia'),
    path('trusted-hosts/', views.trusted_hosts, name='trusted_hosts'),
    path('trusted-hosts/add/', views.trusted_hosts_add, name='trusted_hosts_add'),
    path('trusted-hosts/remove/', views.trusted_hosts_remove, name='trusted_hosts_remove'),
    path('trusted-hosts/wildcard/', views.trusted_hosts_wildcard, name='trusted_hosts_wildcard'),
    path('explorar-docker/', views.explorar_docker, name='explorar_docker'),
    path('navegacion/host/<int:pk>/explorar-docker/', views.explorar_docker_host, name='explorar_docker_host'),
    path('descubrir-tomcat-local/', views.descubrir_tomcat_local, name='descubrir_tomcat_local'),
    path('monitoreo/host/<int:pk>/', views.monitor_snmp_host, name='monitor_snmp_host'),
    path('monitoreo/host/<int:pk>/celery/', views.monitor_host_celery, name='monitor_host_celery'),
]
